app:
  name: "ChatHero"

theme:
  logo: "/assets/logo.svg"
  primaryColor: "#005288"
  secondaryColor: "#A7A9AC"
  backgroundColor: "#ffffff"
  textColor: "#000000"

ai:
  provider: "openai"
  model: "gpt-4o"  # Testing with gpt-4o for all phases
  queryAnalyzerModel: "gpt-4o"  # Use more capable model for Phase 1 query analysis
  apiKey: "${OPENAI_API_KEY}"

dataSource:
  type: "file"
  datasetsPath: "./data"        # Root folder containing dataset subfolders (supports both file and database datasets)
