app:
  name: "ChatHero"

theme:
  logo: "/assets/logo.svg"
  primaryColor: "#005288"
  secondaryColor: "#A7A9AC"
  backgroundColor: "#ffffff"
  textColor: "#000000"

ai:
  provider: "openai"
  model: "gpt-4o-mini"
  apiKey: "${OPENAI_API_KEY}"

dataSource:
  type: "json"
  datasetsPath: "./data"        # Root folder containing dataset subfolders
  defaultDataset: "spacex-launches"  # Default dataset to load
